# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'aws ec2 instance ssh'
        contents: '**'
        targetFolder: '/home/ec2-user'
        readyTimeout: '20000'

    - task: SSH@0
      inputs:
        sshEndpoint: 'aws ec2 instance ssh'
        runOptions: 'commands'
        commands: |
          cd /home/ec2-user
          mkdir docker-folder
        readyTimeout: '20000'