name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 54.166.58.38
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: './'
          target: '/var/www/myapp'
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.166.58.38
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: 'cd /var/www/html && npm install && pm2 restart myapp'
